# Generated by Django 5.0.4 on 2024-04-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daycareapp', '0002_babies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babies',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='babies',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='babies',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='babysitter',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='babysitter',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='babysitter',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='babysitter',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
