# Generated by Django 5.0.4 on 2024-04-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycareapp', '0003_rename_dob_babies_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateTimeField(max_length=20)),
                ('age', models.FloatField(max_length=20)),
                ('parent_name', models.CharField(max_length=20)),
                ('guardian_name', models.CharField(max_length=20)),
                ('parent_phonenummber', models.CharField(max_length=20)),
                ('guardian_phonenumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='babies',
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='date_of_birth',
            field=models.DateTimeField(max_length=20),
        ),
    ]
