# Generated by Django 5.0.4 on 2024-04-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycareapp', '0006_alter_baby_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='email',
            field=models.CharField(default='email', max_length=20),
        ),
    ]
