# Generated by Django 5.0.4 on 2024-04-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycareapp', '0007_babysitter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysitter',
            name='address',
            field=models.CharField(default='address', max_length=20),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='district',
            field=models.CharField(default='district', max_length=20),
        ),
    ]
