# Generated by Django 5.0.4 on 2024-04-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycareapp', '0009_alter_babysitter_address_alter_babysitter_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='babysitter',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=128, null=True),
        ),
    ]
