# Generated by Django 5.0.6 on 2024-05-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycareapp', '0012_procure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dollsdashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('dollsbought', models.FloatField(max_length=5)),
                ('datebought', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
