# Generated by Django 5.0.6 on 2024-05-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycareapp', '0013_dollsdashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schoolfees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_payment', models.CharField(choices=[('Day', 'Day'), ('Halfday', 'Halfday')], max_length=128, null=True)),
                ('amount_paid', models.FloatField(max_length=5)),
                ('date_of_payment', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
