# Generated by Django 5.0.6 on 2024-05-08 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycareapp', '0015_alter_baby_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfees',
            name='baby_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daycareapp.baby'),
        ),
    ]
