# Generated by Django 5.0.6 on 2024-05-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daycareapp', '0016_schoolfees_baby_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolfees',
            old_name='baby_id',
            new_name='baby',
        ),
    ]
